version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./postgresdb/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'edu_db_name'
      POSTGRES_USER: 'edu_user_name'
      POSTGRES_PASSWORD: '123'
